#74 - Criando endpoint de login de usuário.
UnBArqDsw2022-1/2022.1_G5_SerFit_Backend pull request #4
Opened 2022-07-28 21:11 UTC by DanielViniciusAlves

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the CONTRIBUTING.md doc.
- [ ] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-07-28 23:14 UTC, luis-gustavo commented on api/controllers/login.js
> +    validateEmail(email)  {
A validação do email também já está sendo feita pelo sequelize. Não necessariamente precisamos tirar isso, mas está redundante

2022-07-28 23:15 UTC, luis-gustavo commented on api/controllers/login.js
> +        const login = new LoginController();
Pq a login controller está se auto instanciando?

2022-07-28 23:17 UTC, luis-gustavo commented on api/controllers/login.js
> +                const user = await db.user.findOne({ where: { email: email } });
Dá pra passar uma chamada pro sequelize com email e senha, assim evita ter que checar se a senha é igual

2022-07-28 23:18 UTC, luis-gustavo commented on api/controllers/login.js
> +                    message: "Login not successful",
Criar um objeto/classe separado pra conter as mensagens de erro. Assim todos os endpoints ficam com as mensagens iguais

2022-07-28 23:19 UTC, luis-gustavo commented on api/package.json
> +    "sqlite3": "^5.0.10",
Algum motivo pra ter adicionado isso aqui?

2022-07-28 23:20 UTC, luis-gustavo requested changes
Apenas fazer as correções citadas, de resto está show

2022-08-01 11:12 UTC, DanielViniciusAlves commented
Não criei a classe com as mensagens pois acredito que seria mais adequado abir uma issue nova para isso.

2022-08-22 18:43 UTC, DanielViniciusAlves commented
Atualizei a branch e corrigi os conflitos que existiam.

2022-09-07 19:37 UTC, merged